name: Welcome

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to Jordgubble’s MC Java plugins, and thanks for making an issue! We're glad to have you here.'
        pr-message: 'Welcome to Jordgubble’s MC Java plugins, and thanks for making a PR! We're glad to have you here.'
